version: "3"
services:
  dns-worker:
    build:
      context: .
    depends_on:
      - rabbitmq
    environment:
      RABBIT_URL: "amqp://rabbitmq"
      RABBIT_RECIEVE_QUEUE: "dns-query"
      RABBIT_SEND_QUEUE: "dns-result"
  rabbitmq:
    image: rabbitmq:3.7.14-alpine
